-- List of ISO 3166 country codes adapted for DB2
-- Source : https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes?adlt=strict

CREATE OR REPLACE TABLE MYLIBRARY.COUNTRIES (
  ID INTEGER NOT NULL 
    GENERATED ALWAYS AS IDENTITY
    ( START WITH 1 , INCREMENT BY 1 , CACHE 10 )
    UNIQUE,
  CODISO3 CHAR(3) NOT NULL DEFAULT '',
  CODISO2 CHAR(2) NOT NULL DEFAULT '',
  COUNTRYNAM VARCHAR(50) NOT NULL DEFAULT ''
);

LABEL ON TABLE MYLIBRARY.COUNTRIES IS 'List of ISO 3166 country codes';

LABEL ON COLUMN MYLIBRARY.COUNTRIES ( 
  ID IS 'ID du pays' , 
  CODISO3 IS 'Code ISO sur 3c' , 
  CODISO2 IS 'Code ISO sur 2c' , 
  COUNTRYNAM IS 'Nom du pays'
);
   
CREATE INDEX MYLIBRARY.COUNTRIES01 ON MYLIBRARY.COUNTRIES (CODISO3) ;
CREATE INDEX MYLIBRARY.COUNTRIES02 ON MYLIBRARY.COUNTRIES (CODISO2) ;

---------- DATAS ----------

INSERT INTO MYLIBRARY.COUNTRIES (CODISO3, CODISO2, COUNTRYNAM)
VALUES 
 ('AFG ', 'AF ', 'AFGHANISTAN'),
 ('ZAF ', 'ZA ', 'AFRIQUE DU SUD'),
 ('ALA ', 'AX ', 'ALAND, ILES'),
 ('ALB ', 'AL ', 'ALBANIE'),
 ('DZA ', 'DZ ', 'ALGERIE '),
 ('DEU ', 'DE ', 'ALLEMAGNE'),
 ('AND ', 'AD ', 'ANDORRE'),
 ('AGO ', 'AO ', 'ANGOLA'),
 ('AIA ', 'AI ', 'ANGUILLA'),
 ('ATA ', 'AQ ', 'ANTARCTIQUE'),
 ('ATG ', 'AG ', 'ANTIGUA-ET-BARBUDA'),
 ('ANT ', 'AN ', 'ANTILLES NEERLANDAISES '),
 ('SAU ', 'SA ', 'ARABIE SAOUDITE'),
 ('ARG ', 'AR ', 'ARGENTINE'),
 ('ARM ', 'AM ', 'ARMENIE'),
 ('ABW ', 'AW ', 'ARUBA'),
 ('AUS ', 'AU ', 'AUSTRALIE'),
 ('AUT ', 'AT ', 'AUTRICHE'),
 ('AZE ', 'AZ ', 'AZERBAIDJAN'),
 ('BHS ', 'BS ', 'BAHAMAS'),
 ('BHR ', 'BH ', 'BAHREIN'),
 ('BGD ', 'BD ', 'BANGLADESH'),
 ('BRB ', 'BB ', 'BARBADE'),
 ('BLR ', 'BY ', 'BELARUS'),
 ('BEL ', 'BE ', 'BELGIQUE'),
 ('BLZ ', 'BZ ', 'BELIZE'),
 ('BEN ', 'BJ ', 'BENIN '),
 ('BMU ', 'BM ', 'BERMUDES'),
 ('BTN ', 'BT ', 'BHOUTAN'),
 ('BOL ', 'BO ', 'BOLIVIE'),
 ('BIH ', 'BA ', 'BOSNIE-HERZEGOVINE '),
 ('BWA ', 'BW ', 'BOTSWANA'),
 ('BVT ', 'BV ', 'BOUVET, ILE '),
 ('BRA ', 'BR ', 'BRESIL '),
 ('BRN ', 'BN ', 'BRUNEI DARUSSALAM '),
 ('BGR ', 'BG ', 'BULGARIE'),
 ('BFA ', 'BF ', 'BURKINA FASO'),
 ('BDI ', 'BI ', 'BURUNDI'),
 ('CYM ', 'KY ', 'CAIMANES, ILES '),
 ('KHM ', 'KH ', 'CAMBODGE'),
 ('CMR ', 'CM ', 'CAMEROUN'),
 ('CAN ', 'CA ', 'CANADA'),
 ('CPV ', 'CV ', 'CAP-VERT'),
 ('CAF ', 'CF ', 'CENTRAFRICAINE, REPUBLIQUE '),
 ('CHL ', 'CL ', 'CHILI'),
 ('CHN ', 'CN ', 'CHINE'),
 ('CXR ', 'CX ', 'CHRISTMAS, ILE '),
 ('CYP ', 'CY ', 'CHYPRE'),
 ('CCK ', 'CC ', 'COCOS (KEELING), ILES '),
 ('COL ', 'CO ', 'COLOMBIE'),
 ('COM ', 'KM ', 'COMORES'),
 ('COG ', 'CG ', 'CONGO'),
 ('COD ', 'CD ', 'CONGO, LA REPUBLIQUE DEMOCRATIQUE DU '),
 ('COK ', 'CK ', 'COOK, ILES'),
 ('KOR ', 'KR ', 'COREE, REPUBLIQUE DE '),
 ('PRK ', 'KP ', 'COREE, REPUBLIQUE POPULAIRE DEMOCRATIQUE DE '),
 ('CRI ', 'CR ', 'COSTA RICA'),
 ('CIV ', 'CI ', 'COTE D''IVOIRE '),
 ('HRV ', 'HR ', 'CROATIE'),
 ('CUB ', 'CU ', 'CUBA'),
 ('DNK ', 'DK ', 'DANEMARK'),
 ('DJI ', 'DJ ', 'DJIBOUTI'),
 ('DOM ', 'DO ', 'DOMINICAINE, REPUBLIQUE'),
 ('DMA ', 'DM ', 'DOMINIQUE'),
 ('EGY ', 'EG ', 'EGYPTE '),
 ('SLV ', 'SV ', 'EL SALVADOR'),
 ('ARE ', 'AE ', 'EMIRATS ARABES UNIS'),
 ('ECU ', 'EC ', 'EQUATEUR '),
 ('ERI ', 'ER ', 'ERYTHREE'),
 ('ESP ', 'ES ', 'ESPAGNE'),
 ('EST ', 'EE ', 'ESTONIE'),
 ('USA ', 'US ', 'Etats-Unis'),
 ('ETH ', 'ET ', 'ETHIOPIE'),
 ('FLK ', 'FK ', 'FALKLAND, ILES (MALVINAS) '),
 ('FRO ', 'FO ', 'FEROE, ILES '),
 ('FJI ', 'FJ ', 'FIDJI'),
 ('FIN ', 'FI ', 'FINLANDE'),
 ('FRA ', 'FR ', 'FRANCE'),
 ('GAB ', 'GA ', 'GABON'),
 ('GMB ', 'GM ', 'GAMBIE'),
 ('GEO ', 'GE ', 'GEORGIE'),
 ('SGS ', 'GS ', 'GEORGIE DU SUD ET LES ILES SANDWICH DU SUD'),
 ('GHA ', 'GH ', 'GHANA'),
 ('GIB ', 'GI ', 'GIBRALTAR'),
 ('GRC ', 'GR ', 'GRECE '),
 ('GRD ', 'GD ', 'GRENADE'),
 ('GRL ', 'GL ', 'GROENLAND'),
 ('GLP ', 'GP ', 'GUADELOUPE'),
 ('GUM ', 'GU ', 'GUAM'),
 ('GTM ', 'GT ', 'GUATEMALA'),
 ('GGY ', 'GG ', 'GUERNESEY'),
 ('GIN ', 'GN ', 'GUINEE '),
 ('GNB ', 'GW ', 'GUINEE BISSAU '),
 ('GNQ ', 'GQ ', 'GUINEE EQUATORIALE '),
 ('GUY ', 'GY ', 'GUYANA'),
 ('GUF ', 'GF ', 'GUYANE FRANCAISE '),
 ('HTI ', 'HT ', 'HAITI '),
 ('HMD ', 'HM ', 'HEARD, ILE ET MCDONALD, ILES'),
 ('HND ', 'HN ', 'HONDURAS'),
 ('HKG ', 'HK ', 'HONG KONG'),
 ('HUN ', 'HU ', 'HONGRIE'),
 ('IMN ', 'IM ', 'ILE DE MAN '),
 ('UMI ', 'UM ', 'ILES MINEURES ELOIGNEES DES ETATS-UNIS '),
 ('VGB ', 'VG ', 'ILES VIERGES BRITANNIQUES'),
 ('VIR ', 'VI ', 'ILES VIERGES DES ETATS-UNIS '),
 ('IND ', 'IN ', 'INDE'),
 ('IDN ', 'ID ', 'INDONESIE '),
 ('IRN ', 'IR ', 'IRAN, REPUBLIQUE ISLAMIQUE D'' '),
 ('IRQ ', 'IQ ', 'IRAQ'),
 ('IRL ', 'IE ', 'IRLANDE'),
 ('ISL ', 'IS ', 'ISLANDE'),
 ('ISR ', 'IL ', 'ISRAEL '),
 ('ITA ', 'IT ', 'ITALIE'),
 ('JAM ', 'JM ', 'JAMAIQUE '),
 ('JPN ', 'JP ', 'JAPON'),
 ('JEY ', 'JE ', 'JERSEY'),
 ('JOR ', 'JO ', 'JORDANIE'),
 ('KAZ ', 'KZ ', 'KAZAKHSTAN'),
 ('KEN ', 'KE ', 'KENYA'),
 ('KGZ ', 'KG ', 'KIRGHIZISTAN'),
 ('KIR ', 'KI ', 'KIRIBATI'),
 ('KWT ', 'KW ', 'KOWEIT '),
 ('LAO ', 'LA ', 'LAOS, REPUBLIQUE DEMOCRATIQUE POPULAIRE'),
 ('LSO ', 'LS ', 'LESOTHO'),
 ('LVA ', 'LV ', 'LETTONIE'),
 ('LBN ', 'LB ', 'LIBAN'),
 ('LBR ', 'LR ', 'LIBERIA '),
 ('LBY ', 'LY ', 'LIBYENNE, JAMAHIRIYA ARABE'),
 ('LIE ', 'LI ', 'LIECHTENSTEIN'),
 ('LTU ', 'LT ', 'LITUANIE'),
 ('LUX ', 'LU ', 'LUXEMBOURG'),
 ('MAC ', 'MO ', 'MACAO'),
 ('MKD ', 'MK ', 'MACEDOINE, L''EX-REPUBLIQUE YOUGOSLAVE DE '),
 ('MDG ', 'MG ', 'MADAGASCAR'),
 ('MYS ', 'MY ', 'MALAISIE'),
 ('MWI ', 'MW ', 'MALAWI'),
 ('MDV ', 'MV ', 'MALDIVES'),
 ('MLI ', 'ML ', 'MALI'),
 ('MLT ', 'MT ', 'MALTE'),
 ('MNP ', 'MP ', 'MARIANNES DU NORD, ILES'),
 ('MAR ', 'MA ', 'MAROC'),
 ('MHL ', 'MH ', 'MARSHALL, ILES'),
 ('MTQ ', 'MQ ', 'MARTINIQUE'),
 ('MUS ', 'MU ', 'MAURICE'),
 ('MRT ', 'MR ', 'MAURITANIE'),
 ('MYT ', 'YT ', 'MAYOTTE'),
 ('MEX ', 'MX ', 'MEXIQUE'),
 ('FSM ', 'FM ', 'MICRONESIE, ETATS FEDERES DE '),
 ('MDA ', 'MD ', 'MOLDOVA'),
 ('MCO ', 'MC ', 'MONACO'),
 ('MNG ', 'MN ', 'MONGOLIE'),
 ('MNE ', 'ME ', 'MONTENEGRO'),
 ('MSR ', 'MS ', 'MONTSERRAT'),
 ('MOZ ', 'MZ ', 'MOZAMBIQUE'),
 ('MMR ', 'MM ', 'MYANMAR'),
 ('NAM ', 'NA ', 'NAMIBIE'),
 ('NRU ', 'NR ', 'NAURU'),
 ('NPL ', 'NP ', 'NEPAL '),
 ('NIC ', 'NI ', 'NICARAGUA'),
 ('NER ', 'NE ', 'NIGER'),
 ('NGA ', 'NG ', 'NIGERIA '),
 ('NIU ', 'NU ', 'NIUE '),
 ('NFK ', 'NF ', 'NORFOLK, ILE '),
 ('NOR ', 'NO ', 'NORVEGE '),
 ('NCL ', 'NC ', 'NOUVELLE-CALEDONIE'),
 ('NZL ', 'NZ ', 'NOUVELLE-ZELANDE '),
 ('IOT ', 'IO ', 'OCEAN INDIEN, TERRITOIRE BRITANNIQUE DE L'' '),
 ('OMN ', 'OM ', 'OMAN'),
 ('UGA ', 'UG ', 'OUGANDA'),
 ('UZB ', 'UZ ', 'OUZBEKISTAN '),
 ('PAK ', 'PK ', 'PAKISTAN'),
 ('PLW ', 'PW ', 'PALAOS'),
 ('PSE ', 'PS ', 'PALESTINIEN OCCUPE, TERRITOIRE'),
 ('PAN ', 'PA ', 'PANAMA'),
 ('PNG ', 'PG ', 'PAPOUASIE-NOUVELLE-GUINEE '),
 ('PRY ', 'PY ', 'PARAGUAY'),
 ('NLD ', 'NL ', 'PAYS-BAS'),
 ('PER ', 'PE ', 'PEROU '),
 ('PHL ', 'PH ', 'PHILIPPINES'),
 ('PCN ', 'PN ', 'PITCAIRN'),
 ('POL ', 'PL ', 'POLOGNE'),
 ('PYF ', 'PF ', 'POLYNESIE FRANCAISE '),
 ('PRI ', 'PR ', 'PORTO RICO'),
 ('PRT ', 'PT ', 'PORTUGAL'),
 ('QAT ', 'QA ', 'QATAR'),
 ('REU ', 'RE ', 'REUNION '),
 ('ROU ', 'RO ', 'ROUMANIE'),
 ('GBR ', 'GB ', 'ROYAUME-UNI'),
 ('RUS ', 'RU ', 'RUSSIE, FEDERATION DE '),
 ('RWA ', 'RW ', 'RWANDA'),
 ('ESH ', 'EH ', 'SAHARA OCCIDENTAL'),
 ('BLM ', 'BL ', 'SAINT-BARTHELEMY'),
 ('KNA ', 'KN ', 'SAINT-KITTS-ET-NEVIS'),
 ('SMR ', 'SM ', 'SAINT-MARIN'),
 ('MAF ', 'MF ', 'SAINT-MARTIN (PARTIE FRANCAISE) '),
 ('SPM ', 'PM ', 'SAINT-PIERRE-ET-MIQUELON'),
 ('VAT ', 'VA ', 'SAINT-SIEGE (ETAT DE LA CITE DU VATICAN)'),
 ('VCT ', 'VC ', 'SAINT-VINCENT-ET-LES GRENADINES'),
 ('SHN ', 'SH ', 'SAINTE-HELENE'),
 ('LCA ', 'LC ', 'SAINTE-LUCIE'),
 ('SLB ', 'SB ', 'SALOMON, ILES '),
 ('WSM ', 'WS ', 'SAMOA'),
 ('ASM ', 'AS ', 'SAMOA AMERICAINES '),
 ('STP ', 'ST ', 'SAO TOME-ET-PRINCIPE '),
 ('SEN ', 'SN ', 'SENEGAL '),
 ('SRB ', 'RS ', 'SERBIE'),
 ('SYC ', 'SC ', 'SEYCHELLES'),
 ('SLE ', 'SL ', 'SIERRA LEONE'),
 ('SGP ', 'SG ', 'SINGAPOUR'),
 ('SVK ', 'SK ', 'SLOVAQUIE'),
 ('SVN ', 'SI ', 'SLOVENIE'),
 ('SOM ', 'SO ', 'SOMALIE'),
 ('SDN ', 'SD ', 'SOUDAN'),
 ('LKA ', 'LK ', 'SRI LANKA'),
 ('SWE ', 'SE ', 'SUEDE '),
 ('CHE ', 'CH ', 'SUISSE'),
 ('SUR ', 'SR ', 'SURINAME'),
 ('SJM ', 'SJ ', 'SVALBARD ET ILE JAN MAYEN '),
 ('SWZ ', 'SZ ', 'SWAZILAND'),
 ('SYR ', 'SY ', 'SYRIENNE, REPUBLIQUE ARABE '),
 ('TJK ', 'TJ ', 'TADJIKISTAN'),
 ('TWN ', 'TW ', 'TAIWAN, PROVINCE DE CHINE'),
 ('TZA ', 'TZ ', 'TANZANIE, REPUBLIQUE UNIE DE'),
 ('TCD ', 'TD ', 'TCHAD'),
 ('CZE ', 'CZ ', 'TCHEQUE, REPUBLIQUE '),
 ('ATF ', 'TF ', 'TERRES AUSTRALES FRANCAISES'),
 ('THA ', 'TH ', 'THAILANDE'),
 ('TLS ', 'TL ', 'TIMOR-LESTE'),
 ('TGO ', 'TG ', 'TOGO'),
 ('TKL ', 'TK ', 'TOKELAU'),
 ('TON ', 'TO ', 'TONGA'),
 ('TTO ', 'TT ', 'TRINITE-ET-TOBAGO '),
 ('TUN ', 'TN ', 'TUNISIE'),
 ('TKM ', 'TM ', 'TURKMENISTAN '),
 ('TCA ', 'TC ', 'TURKS ET CAIQUES, ILES'),
 ('TUR ', 'TR ', 'TURQUIE'),
 ('TUV ', 'TV ', 'TUVALU'),
 ('UKR ', 'UA ', 'UKRAINE'),
 ('URY ', 'UY ', 'URUGUAY'),
 ('VUT ', 'VU ', 'VANUATU'),
 ('VEN ', 'VE ', 'VENEZUELA'),
 ('VNM ', 'VN ', 'VIET NAM'),
 ('WLF ', 'WF ', 'WALLIS-ET-FUTUNA'),
 ('YEM ', 'YE ', 'YEMEN '),
 ('ZMB ', 'ZM ', 'ZAMBIE'),
 ('ZWE ', 'ZW ', 'ZIMBABWE');